acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /kek

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_controller:
    resource: "@UserBundle/Controller"
    prefix: /
    type: annotation