Acme\TestBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: Acme\TestBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
